name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag test:$(date +%s)

    - name: Run the Docker container
      run: |
        # Run the Docker container in the background
        docker run -d -p 8334:8334 test:$(date +%s)  # Make sure to expose the correct port

    - name: Get the URL
      run: echo "Service is running at http://localhost:8334"
